# Defining the optimizer as a group default allows CLI override, e.g.
# python train.py "optimizer@model.optimizer=sgd"
# or via config "override scheduler@model.scheduler: cyclic"
# See https://stackoverflow.com/questions/71438040/overwriting-hydra-configuration-groups-from-cli/71439510#71439510
defaults:
  - /optimizer@optimizer: adam
  - /scheduler@scheduler: plateau

name: SimSiam

nn:
  _target_: autoencoders.models.simsiam.SimSiam
  encoder:
    _target_: autoencoders.models.simsiam.CNNEncoderProjection
    channels_in: 1
    base_channels: 32
    latent_dim: ${model.nn.dim}
  dim: 512
  pred_dim: 512
