version: "3"

# You can also ask Task to include .env like files by using the dotenv: setting:
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

# If `--` is given in the CLI, all following parameters are added to a special .CLI_ARGS variable.
# This is useful to forward arguments to another command.

tasks:

  check-config:
    desc: Check Hydra configuration
    cmds:
      - python autoencoders/train.py --cfg all --resolve {{.CLI_ARGS}}

  wandb:
    desc: Login to Weights & Biases
    cmds:
      - wandb login $WANDB_KEY

  train:
    desc: Train a model
    cmds:
      - python autoencoders/train.py {{.CLI_ARGS}}

  eval-downstream:
    desc: Evaluate encoders using linear baselines
    cmds:
      - python autoencoders/compare.py {{.CLI_ARGS}}
    sources:
      - autoencoders/conf/comps.yaml
      - autoencoders/compare.py
    generates:
      - outputs/comps.json

  plot-downstream:
    desc: Plot encoder performance on downstream tasks
    cmds:
      - python autoencoders/plot.py {{.CLI_ARGS}}
    sources:
      - outputs/comps.json
      - autoencoders/plot.py
    generates:
      - outputs/encoder-auc.png
      - outpuers/encoder-accuracy.png

  compare:
    desc: Compare encoders using linear baselines
    cmds:
      - task: eval-downstream
      - task: plot-downstream
